name: Retraining Pipeline

on:
  workflow_dispatch:
    inputs:
      run_notebooks:
        description: 'Run data prep & model training notebooks'
        required: true
        default: 'false'

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install training dependencies
        run: |
          pip install -r requirements.txt
          pip install papermill

      - name: Run data preparation notebook
        if: github.event.inputs.run_notebooks == 'true'
        run: |
          papermill notebooks/data_prep.ipynb notebooks/data_prep_output.ipynb

      - name: Run model training notebook
        if: github.event.inputs.run_notebooks == 'true'
        run: |
          papermill notebooks/model_training.ipynb notebooks/model_training_output.ipynb

      - name: Build & push Docker container
        run: |
          docker build -t your_dockerhub_username/transport-forecasting:latest .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push your_dockerhub_username/transport-forecasting:latest
